apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pfe-argo
  namespace: argocd
spec:
  destination:
    namespace: pfe
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    repoURL: https://github.com/Cyberkabil10/app-pfe-backend.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    #syncOptions:
    #- CreateNamespace=true
