apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-auth-config
  namespace: pfe
  labels:
    app: pfeapp
data:
  application.properties: |-
    #server.servlet.context-path=/oauth/token
    #spring.mvc.servlet.path=/auth
    server.port=9100
    spring.datasource.username=root
    spring.datasource.password=${MYSQL_ROOT_PASSWORD}
    spring.datasource.url= jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    spring.datasource.driverClassName=com.mysql.jdbc.Driver
    spring.jpa.show-sql=true
    spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
    spring.jpa.generate-ddl=true
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
    spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext

    #========================
    check-user-scopes=true
    spring.main.allow-bean-definition-overriding=true
    #======================
    spring.mail.host=mail.exis-it.com
    spring.mail.username=guide@exis-it.com
    spring.mail.password=eXis.2019+
    spring.mail.properties.mail.smtp.auth=true
    spring.mail.properties.mail.smtp.ssl.enable = true
    spring.mail.properties.mail.smtp.socketFactory.port = 465
    spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory
    spring.mail.properties.mail.smtp.socketFactory.fallback = false
    exisauth.thread.core-pool=10
    exisauth.thread.max-pool=100
    exisauth.queue.capacity=50
    exisauth.thread.timeout=120