apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  namespace: pfe
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  rules:
  - host: kabil-aws-pfe.com
    http:
      paths:
        - pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 90
          path: /
        - pathType: Prefix
          backend:
            service:
              name: backend-service
              port:
                number: 8891
          path: /api
        - pathType: Prefix
          backend:
            service:
              name: backend-auth-service
              port:
                number: 9100
          path: /oauth/token
  tls:
  - hosts:
    - kabil-aws-pfe.com
    secretName: laugh-tale-secret-one-piece
