apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  #namespace: pfe
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kabil.benhamda@esprit.tn
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
